[package]
name = "stark-101-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zkp-libs = { path = "/home/alex/repos/zkp-libs" }
rand = "0.8"
